app = 'fastivite'
primary_region = 'arn'


[mounts]
source = "htmlcache"
destination = "/htmlcache"


[env]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "3000"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2
